### ISSUE TITLE
Guardian state release conditions

### ISSUE THREAD

**Issue by OmarDahmen** [bluelibs/bluelibs#237]
**Describe the bug**
`guardian` and `guardian.state` are not matching values.

**To Reproduce**
Here is the code (in `Home.tsx`) :
```
  const guardian = useGuardian();
  const router = useRouter();

  useEffect(() => {
    if (!guardian.state.fetchingUserData) {
      console.log("guardian", guardian);
      console.log("guardian.state", guardian.state);
      console.log("guardian.state.isLoggedIn :", guardian.state.isLoggedIn);
      const user = guardian.state.user;
      console.log("user", user);
      if (guardian.state.isLoggedIn) {
        router.go(
          hasRoles([UserRoles.SUPPORT], user)
            ? Routes.CLIENT_REQUESTS_LIST
            : hasRoles([UserRoles.PLUMBER], user)
            ? Routes.QUOTATIONS_KANBAN
            : hasRoles([UserRoles.ADMIN], user) && Routes.DASHBOARD,
        );
      } else {
        router.go(Routes.LOGIN);
      }
    }
  }, [guardian.state.fetchingUserData, guardian.state.isLoggedIn]);

```

**Expected behavior**
```
guardian {
  ...
  state {
    ...
    isLoggedIn: VALUE
  }
}
```
and 
```guardian.state.isLoggedIn```
should have the same value !
(take a look at the screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/21100856/157225478-5471eb50-24c6-4060-8bbf-fe714ad47064.png)

**Comment by Fen747** [comment]
The thing here is that we also run into what looks like a race condition, where `isLoggedIn` becomes `true` only after `fetchingUserData` becomes false, (like if their respective `setState` was not batched / happened on different frames), making it difficul to properly work with it.

We should be able to have such a condition :
- When fetching data is over, check if we are logged in : if not, then we assume the token is invalid and redirect to login.

But that requires to ensure `fetchingUserData` and `isLoggedIn` are updated at the exact same moment

**Comment by y-moufakkr** [comment]
correct me if I m wrong, but I think its working how its supposed to work, the guardian object is not a state so we cant rely on  `console.log(guardian)` to decide our situation in fetching things, in fact if you do a useEffect on variable guardian.state and for example the process logged 4 times inside useEffect, you will notice that the `console.log(guardian)` doesnt change and it equals to the last `console.log(guardian.state)` and those 4 `console.logs(guardian.state)` represent the path that our variables took,
so in you shoes I ll just forget about the guardian when I wanna know the state and focus on guardianh.state,
for the relation between fetchingUserData and isLoggedIn, I also belive its correct fetchingUserData  is like a loading boolean and isLoggedin is our results so its supposed to work like that

**Comment by theodorDiaconu** [comment]
@OmarDahmen is this solved?

**Comment by y-moufakkr** [comment]
hello I'm kind of confused, when you say "erroneously forcing re-routing", means that redirecting  to login page is unwanted  when `isLoggedin:false` and ` fetchingUserData:false` , data is bad, can you share with us please the wanted behavior,

note that the guardian attribute `fetchingUserData` doesnt stay on it initial state , it passes from false to true to false,
but because there s no token we keep it false, from my understanding you wish to see that state of true in your home component right ? if so I can set `fetchingUserData`:true before searching for the token en making it false again when we cant find it, but I cant see why we need that

**Comment by y-moufakkr** [comment]
ok I get it now, but its still as I said,let me explain: 
**when token is there** : `fetchingUserData` goes from ( false: initial value ) to (true: while we r fetching the user info from backend) to (false: we got response either we log in user or invalid token)
**in the case of token not stored** : we dont even bother to  change `fetchingUserData` because there s no token, 
so the false you r getting its not an initial value,

but I know understand the redirect case you r trying to avoid, and the answer to that is simply use `gaurdian.state.initialised` so basically `gaurdian.state `shouldnt be played with unless the `gaurdian.state.initialised===true`
