### ISSUE TITLE
Nova: Using nested _id field for link prevents loading the full parent object with objectKey: 1

### ISSUE THREAD

**Issue by Twisterking** [bluelibs/bluelibs#336]
Let's say you have 2 collections, called `OrderItems` and `Products`.

The `OrderItems` save the product at the point in time when an order is placed like so:

```js
{
  _id: ...,
  orderId: ...,
  product: {
    _id,
    ref,
    name,
    ...
  }
}
```

So we can (should be able to) load the full product in a query like so:

```js 
{
  _id: 1,
  orderId: 1,
  product: 1
}
```

In addition to that, we created a link between the 2 collections to also load the `currentProduct` for an orderItem, in case the product still exists in the database:

```js
addLinks(Collections.OrderItems, {
  currentProduct: {
    collection: () => Collections.Products,
    field: 'product._id',
    many: false
  }
});
```

Like this, we can now use `currentProduct` in our nova queries to also populate the current product. All good! ✌️ 

**BUT: The "bug" now is this:**

With this setup we can NOT just load the full `product` object in a query by defining `product: 1` in the query - this just results in an empty object (`{ ..., product: {} }`)!
We now have to define ALL keys we want to load like this:

```js
{
  _id: 1,
  orderId: 1,
  product: {
    _id: 1,
    ref : 1,
    name: 1,
    ...
  }
}
```

Why is that? Is this a bug? is this intended behaviour? It is a bit weird to me. 
We are sure that the link is the root cause here, because if we just remove the link, we CAN load the full product again by just putting `product: 1` in the query.

**Comment by theodorDiaconu** [comment]
It's by design like this. But we have an `$all` parameter. https://www.bluelibs.com/docs/package-nova/#high-performance-queries

It's typically used for performance in some cases because we'd rather prefer you have type safety and explicit request. The reason is security, it's harder to forget that when you add a new field, you expose it to all queries that request {product: 1}. This basically gives you fine grained control, and as your model evolves your bandwidth might not grow directly proportional with it. 

Either way, you have the flexibility to work with it how you wish.

**Comment by Twisterking** [comment]
Thanks a lot for your reply Theo! ✌️
